---
title: "EVT"
author: "Yuan Zhuang"
date: "2024-04-15"
output: html_document
---
# 3.2.4

```{r, warning=FALSE, message=FALSE}
library(QRM)
library(brms)
x <- seq(from = -5, to = 5, length.out = 10000)
dens_gumbel <- dGumbel(x, mu = 0, sigma = 1, log = FALSE)
dens_weibull <- ifelse(x > 0, 0, exp(x))
dens_frechet <- dfrechet(x, loc = 0, scale = 1, shape = 1)
plot(x, dens_gumbel, col = "blue",xlab = "x",ylab ="Density",lwd = 0.5, cex = 0.25, ylim = c(0,1))
lines(x, dens_weibull, col = "red")
lines(x, dens_frechet, col = "green")
legend("topright",pch=c(15,15),legend=c("Weibull","Gumbel","Fréchet"),col=c("red","blue","green"),bty="n")
```

# 3.2.9
## Up
```{r, warning=FALSE, message=FALSE}
library(QRM)
library(brms)
x <- seq(from = -2, to = 5, length.out = 10000)
df_gumbel <- pGumbel(x, mu = 0, sigma = 1)
exp_5 <- pexp(x+log(5))^5
exp_10 <- pexp(x+log(10))^10
plot(x, df_gumbel, col = "blue",xlab = "x",ylab ="Relative Error",lwd = 0.5, cex = 0.25, ylim = c(0,1))
lines(x, exp_5, col = "red")
lines(x, exp_10, col = "green")
legend("topright",pch=c(15,15),legend=c("Gumbel","n = 5","n = 10"),col=c("blue","red","green"),bty="n")
```

## Down
```{r, warning=FALSE, message=FALSE}
exp_5_error <- (1-pexp(x+log(5))^5)/(1-df_gumbel)-1
exp_10_error <- (1-pexp(x+log(10))^10)/(1-df_gumbel)-1
exp_20_error <- (1-pexp(x+log(20))^20)/(1-df_gumbel)-1
plot(x, exp_5_error, col = "blue",xlab = "x",ylab ="DF",lwd = 0.5, cex = 0.25, ylim = c(0,0.08))
lines(x, exp_10_error, col = "red")
lines(x, exp_20_error, col = "green")
legend("topright",pch=c(15,15),legend=c("n = 5","n = 10","n = 20"),col=c("blue","red","green"),bty="n")
```

# 3.2.10
## Up
```{r}
df_frechet <- pfrechet(x, loc = 0, scale = 1, shape = 1)
cauchy_5 <- pcauchy(x*5/pi)^5
cauchy_10 <- pcauchy(x*10/pi)^10
plot(x, df_frechet, col = "blue",xlab = "x",ylab ="DF",lwd = 0.5, cex = 0.25, ylim = c(0,1))
lines(x, cauchy_5, col = "red")
lines(x, cauchy_10, col = "green")
legend("topright",pch=c(15,15),legend=c("Fréchet","n = 5","n = 10"),col=c("blue","red","green"),bty="n")
```

## Down
```{r}
x <- seq(from = -2, to = 20, length.out = 100000)
df_frechet <- pfrechet(x, loc = 0, scale = 1, shape = 1)
cauchy_5_error <- (1-pcauchy(x*5/pi)^5)/(1-df_frechet)-1
cauchy_10_error <- (1-pcauchy(x*10/pi)^10)/(1-df_frechet)-1
cauchy_20_error <- (1-pcauchy(x*20/pi)^20)/(1-df_frechet)-1
plot(x, cauchy_5_error, col = "blue",xlab = "x",ylab ="Relative Error",lwd = 0.5, cex = 0.25, xlim = c(0,20), ylim = c(-0.08,0.02))
lines(x, cauchy_10_error, col = "red")
lines(x, cauchy_20_error, col = "green")
legend("topright",pch=c(15,15),legend=c("n = 5","n = 10","n = 20"),col=c("blue","red","green"),bty="n")
```

